name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
    paths:
      - 'release-versions/latest.txt'

jobs:
  publish:
    name: Push new release version image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set environment
        run: |
          cat >>"${GITHUB_ENV}" <<-EOF
          RELEASE_VERSION=$(cat release-versions/latest.txt)
          CALIBRE_VERSION=$(cat release-versions/calibre.txt)
          FFF_VERSION=$(cat release-versions/fff.txt)
          REF=${REF}
          REPO=${REPO,,}
          EOF
        env:
          REF: ${{ github.ref_name }}
          REPO: ${{ github.repository }}

      - name: Print image tag
        run: |
          echo "Branch: ${REF}"
          echo "Release Version: ${RELEASE_VERSION}"
          echo "Calibre Version: ${CALIBRE_VERSION}"
          echo "FFF Version: ${FFF_VERSION}"
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ env.RELEASE_VERSION }}
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
            CALIBRE_RELEASE=${{ env.CALIBRE_VERSION }}
            FFF_RELEASE=${{ env.FFF_VERSION }}
